using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProblemLogic
{
    public class ProblemsOneToTen
    {
        public static bool IsPrime(long number)
        {
            if (number == 1) return false;
            if (number == 2) return true;

            var sqrtOfNumberBeingChecked = (long)Math.Floor(Math.Sqrt(number));
            for (long b = 2; b <= sqrtOfNumberBeingChecked; b++)
            {
                if (number % b == 0) return false;
            }
            return true;
        }

        #region One
        //If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

        //Find the sum of all the multiples of 3 or 5 below 1000.

        public static long SumOfMultiplesOf3And5BelowArgument(int belowThisNumber)
        {
            long a = 0;
            for (long i = 0; i < belowThisNumber; i++)
            {
                if (i % 3 == 0 || i % 5 == 0) a += i;
            }
            return a;
        }
        #endregion

        #region Two
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        public static int GetSumOfEvenFibonacciNumbersBelowGivenArgument(int maximumFibonacciNumber)
        {
            int a = 0;
            int b = 1;
            int sumofEvenFibonacciNumbers = 0;

            while (a < maximumFibonacciNumber)
            {
                int temp = a;
                a = b;
                b = temp + b;

                if (a % 2 == 0) sumofEvenFibonacciNumbers += a;
            }
            return sumofEvenFibonacciNumbers;
        }
        #endregion

        #region Three
        //The prime factors of 13195 are 5, 7, 13 and 29.

        //What is the largest prime factor of the number 600851475143 ?

        public static long LargestPrimeFactor(long number)
        {
            long maximumPrimeFactor = 0;

            var sqrtOfNumberBeingChecked = (long)Math.Floor(Math.Sqrt(number));

            for (long i = 1; i < sqrtOfNumberBeingChecked; i++)
            {
                if (number % i == 0 && IsPrime(i))
                {
                    if (i > maximumPrimeFactor) maximumPrimeFactor = i;
                }
            }
            return maximumPrimeFactor;
        }
        #endregion

        #region Four
        //A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

        //Find the largest palindrome made from the product of two 3-digit numbers.


        public static int LargestPalindromeProductOfTwoThreeDigitNumbers()
        {
            int maximumProduct = 0;

            for (int i = 100; i < 999; i++)
            {
                for (int j = 100; j < 999; j++)
                {
                    int product = i * j;
                    char[] productArray = product.ToString().ToArray();
                    char[] reverseProductArray = product.ToString().Reverse().ToArray();
                    string stringOfProduct = new string(productArray);
                    string reverseStringOfProduct = new string(reverseProductArray);
                    if (stringOfProduct == reverseStringOfProduct && product > maximumProduct)
                    {
                        maximumProduct = product;
                    }
                }
            }
            return maximumProduct;
        }
        #endregion

        #region Five
        //2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

        //What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

        public static long SmallestMultiple()
        {
            for (long i = 1; i < Int64.MaxValue; i++)
            {
                if (i % 20 == 0 && i % 19 == 0 && i % 18 == 0 && i % 17 == 0 && i % 16 == 0 && i % 15 == 0 && i % 14 == 0 && i % 13 == 0 && i % 11 == 0)
                {
                    return i;
                }
            }
            return 0;
        }
        #endregion

        #region Six
        //The sum of the squares of the first ten natural numbers is,

        //1^2 + 2^2 + ... + 10^2 = 385
        //The square of the sum of the first ten natural numbers is,

        //(1 + 2 + ... + 10)^2 = 552 = 3025
        //Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
        //Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

        public static double SumOfSquares()
        {
            List<double> listOfSquares = new List<double>();

            for (double i = 0; i <= 100; i++)
            {
                double squaredValues = Math.Pow(i, 2);
                listOfSquares.Add(squaredValues);
            }

            double sumOfSquaredValues = listOfSquares.Sum();
            return sumOfSquaredValues;
        }

        public static double SquareOfSums()
        {
            List<double> listOfValuesTo100 = new List<double>();

            for (double i = 0; i <= 100; i++)
            {
                listOfValuesTo100.Add(i);
            }

            double sumOfValues = listOfValuesTo100.Sum();
            double squareOfSum = Math.Pow(sumOfValues, 2);
            return squareOfSum;
        }

        public static double SumSquareDifference()
        {
            double x = SquareOfSums() - SumOfSquares();
            return x;
        }
        #endregion

        #region Seven
        //By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

        //What is the 10 001st prime number?
        public static long GetPrimeByIndex(long indexOfPrimeWanted)
        {
            long index = 1;
            long j = 1;
            while (index <= indexOfPrimeWanted)
            {
                if (IsPrime(j))
                {
                    if (index == indexOfPrimeWanted) return j;
                    index++;
                }
                j++;
            }
            return 0;
        }
        #endregion

        #region Eight
        //The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

        //73167176531330624919225119674426574742355349194934
        //96983520312774506326239578318016984801869478851843
        //85861560789112949495459501737958331952853208805511
        //12540698747158523863050715693290963295227443043557
        //66896648950445244523161731856403098711121722383113
        //62229893423380308135336276614282806444486645238749
        //30358907296290491560440772390713810515859307960866
        //70172427121883998797908792274921901699720888093776
        //65727333001053367881220235421809751254540594752243
        //52584907711670556013604839586446706324415722155397
        //53697817977846174064955149290862569321978468622482
        //83972241375657056057490261407972968652414535100474
        //82166370484403199890008895243450658541227588666881
        //16427171479924442928230863465674813919123162824586
        //17866458359124566529476545682848912883142607690042
        //24219022671055626321111109370544217506941658960408
        //07198403850962455444362981230987879927244284909188
        //84580156166097919133875499200524063689912560717606
        //05886116467109405077541002256983155200055935729725
        //71636269561882670428252483600823257530420752963450

        //Find the thirteen adjacent digits in the 1000-digit number that have the greatest product.What is the value of this product?

        public static long GetLargestProduct()
        {
            string number = "73167176531330624919225119674426574742355349194934" +
                            "96983520312774506326239578318016984801869478851843" +
                            "85861560789112949495459501737958331952853208805511" +
                            "12540698747158523863050715693290963295227443043557" +
                            "66896648950445244523161731856403098711121722383113" +
                            "62229893423380308135336276614282806444486645238749" +
                            "30358907296290491560440772390713810515859307960866" +
                            "70172427121883998797908792274921901699720888093776" +
                            "65727333001053367881220235421809751254540594752243" +
                            "52584907711670556013604839586446706324415722155397" +
                            "53697817977846174064955149290862569321978468622482" +
                            "83972241375657056057490261407972968652414535100474" +
                            "82166370484403199890008895243450658541227588666881" +
                            "16427171479924442928230863465674813919123162824586" +
                            "17866458359124566529476545682848912883142607690042" +
                            "24219022671055626321111109370544217506941658960408" +
                            "07198403850962455444362981230987879927244284909188" +
                            "84580156166097919133875499200524063689912560717606" +
                            "05886116467109405077541002256983155200055935729725" +
                            "71636269561882670428252483600823257530420752963450";

            char[] charArray = number.ToArray();
            int n = 0;
            long maxProduct = 0;

            while (n < 988)
            {
                long a = 1;
                for (int i = n; i <= n + 12; i++)
                {
                    long b = Convert.ToInt64(charArray[i].ToString());
                    long temp = a;
                    b *= temp;
                    a = b;

                    if (i == n + 12 && maxProduct < b)
                    {
                        maxProduct = b;
                    }
                }
                n++;
            }
            return maxProduct;
        }
        #endregion

        #region Nine
        //A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

        //a^2 + b^2 = c^2
        //For example, 3^2 + 4^2 = 9 + 16 = 25 = 5^2.

        //There exists exactly one Pythagorean triplet for which a + b + c = 1000.
        //Find the product abc.

        public static int GetProductOfPythagoreanTriplet(int number)
        {
            int a = 1;
            int b = 1;
            int c = 1;

            while (a < number)
            {
                while (b < number)
                {
                    while (c < number)
                    {
                        if ((a * a) + (b * b) == (c * c) && a < b && b < c && a + b + c == number)
                        {
                            return (a * b * c);
                        }
                        c++;
                    }
                    c = 1;
                    b++;
                }
                b = 1;
                a++;
            }
            return 0;
        }

        #endregion

        #region Ten

        //The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.

        //Find the sum of all the primes below two million.

        public static long SumOfPrimesBelowValueProvided(int maxValue)
        {
            long a = 1;
            long sumofPrimes = 0;

            while (a <= maxValue)
            {
                if (IsPrime(a)) sumofPrimes += a;
                a++;
            }
            return sumofPrimes;
        }
        #endregion
    }
}
